theme: jekyll-theme-cayman
title: Gökmen Görgen
description: Software Developer / Bassist
keywords: python, django, java, android, dotnet, xamarin, nodejs, javascript, türkiye, istanbul
show_downloads: false
google_analytics: UA-54304543-3
