theme: jekyll-theme-cayman
title: Gökmen Görgen
description: Pythonista, Djangonaut, interested in ML / AI and loves bass guitar
keywords: python, django, java, android, dotnet, xamarin, nodejs, javascript, türkiye, istanbul
show_downloads: false
google_analytics: UA-54304543-3
